services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todouser
      DB_PASSWORD: todopass
    depends_on:
      - "db"

  app2:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todouser
      DB_PASSWORD: todopass
    depends_on:
      - "db"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - "app1"
      - "app2"

volumes:
  postgres_data: