services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todouser
      DB_PASSWORD: todopass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "db"

  app2:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todouser
      DB_PASSWORD: todopass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "db"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - "app1"
      - "app2"

  redis:
    image: redis:7-alpine

volumes:
  postgres_data: